### PR TITLE
Solve the issue when "Source reference" is set to any J3 files set.

### PR DESCRIPTION
**Pull request by Valc**
@infograf768 
From "Options" do this  is actualy bugged due it never will get files with standarised format names:

oldhormatdiff5

I have simply modified the "helper" functions than were issued, to be able after patch to handle it automatically when detected and then store a right and valid format file names at "media customisedref github" folder.

oldhormatdiff3

All the en-GB sets that are stored at "media customisedref github" folder never will overwrite the "local installed instace", so, i think is better be able to get the diff from the J3 sets at J4 than "delete" the "J3 options" from the soure reference field list.

oldhormatdiff

For those who start translating J4 from a J3 language pack (also installable at J4), can to be useful get the close to 600 or more text changes present between both branches XD.

Only at installarion folder now are detected 52 keys with changed text:

oldhormatdiff2

oldhormatdiff4

### CODE REVIEW

**Comment by infograf768** [comment]
Good find!

The PR does not delete the downloaded files with tag.
Screen Shot 2021-09-26 at 09 49 33

Do we need to keep them ?

I tested deleting them manually and it looks like it still works fine and does not download them again.

**Comment by Valc** [comment]
@infograf768

> Do we need to keep them ?

I think yes.

In other modules that I developed I used that "not ini" files reference to know if something has been added or removed from there from the Official Project.

That is, if one day from the OP the "localise.php" is removed or the "pim.xml" is added, it could be known easily and warned.

I do not remember if when I touched that code years ago I implemented this that I comment, but surely I left the structure ready to be able to do it.

If they are not used at the moment, I think they do not bother either :D

**Comment by infograf768** [comment]
> If they are not used at the moment, I think they do not bother either :D

They represent around 1.7 MB on disk (750 000 bytes)  for  3.10.2 admin only. That is why I asked.

Lets merge it anyway. Can be improved later.

**Comment by infograf768** [comment]
Thanks

**Comment by Valc** [comment]
> They represent around 1.7 MB on disk (750 000 bytes) for 3.10.2 admin only. That is why I asked.

I think is easy to solve if is simply delete all "en-GB." files matches when "J3" case is detected.

Now i am still working at "not in reference" PR.

At first moment I did not understand rightly your question, but yes, attepmt it previous patch also include all "en-GB. inis" set fro all seleected clients.

I can take a look later and send a new PR when already merged this one,  :D

**Pull request merged**
