### PR TITLE
Solving our Custom Field cases issues

### PR DESCRIPTION
**Pull request by Valc**
At the end, i has been not able to send the zip by mail,
I hope can help you.
Regards.

### CODE REVIEW

**Comment by infograf768** [comment]
@Valc 
Type never has uppercase first letter. It's always lowercase.
See com_content forms in J4.

OK for the name of fields but a question: have you remarked that these corrections solve some issues?

**Comment by Valc** [comment]
@infograf768
> OK for the name of fields but a question: have you remarked that these corrections solve some issues?


Yes, at our forum, but i can repeat also here:
**START**
Hi JM:

The truth is that I have very bad time to set up the work environment and I will have to start seeing how I do it this weekend.

In the meantime, I'll share with you what I have made progress in relation to our custom fields.

Basically it was all done and it was just minor tweaks to syntax issues (congrats your job there is not a basic draft such as the main repo).

Now all the fields name files in the "Field" folder begin with a capital letter and end in "Field", which is what corresponds to the name that had been given to them within most of those files from:

```
class LanguageclientField extends ListField
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since   3.9.0
	 */
	protected $type = 'Languageclient';
```
Finally, in all the xml that are to load forms, I have modified the "type" so that it starts with capital letters when is one of our custom fields and, to all the custom fields within the xml I have added the line:

```
	<field
		name="language_client"
		type="Languageclient"
		label="COM_LANGUAGES_OVERRIDE_SELECT_LANGUAGECLIENT"
		onchange="this.form.submit();"
		filtermode="selector"
		addfieldprefix="Joomla\Component\Languages\Administrator\Field"
		>
		<option value="">COM_LANGUAGES_OVERRIDE_SELECT_LANGUAGE</option>
	</field>
```
Also noticed that this can also be added directly at form tag with same result:

`<form addfieldprefix="Joomla\Component\Localise\Administrator\Field">`

I don't know if this is the best way, but having managed to make one work, I have applied it to the rest.

I am attaching the pack so that you can try and if you think it is convenient to do the PR.
now
now2

Edited: Sorry, i cant attach the zip due limit exced. Let me know what mail address to use to send it by mail
Greetings, Valc.

**END**

Then, by mail i was not able to send you the package due was rejected by gmail (unallowed extensions type i think).


With your released beta2  i was not able to make run the "Options" fields than mathes with our cystom fields, and without that ones crashed, no many stuff was working fine and here is the pull request tryinf to solve it :)

**Comment by infograf768** [comment]
Type IN THE XML is always lowercase. ;)

**Comment by infograf768** [comment]
generally speaking: please correct this PR as some changes are no use. See above.
Discuss com_localise code only in this repo, not in the forum. 😄

**Comment by Valc** [comment]
> Discuss com_localise code only in this repo, not in the forum.

Yep, you are right, simply is that my firts attenpt were to send to you a package and not a PR.

> generally speaking: please correct this PR as some changes are no use. See above.
I think is done such as you explain now
As i say before at other comment, please, resolve the case with your best code lines implementation if the mines are not the best option :)

**Comment by Valc** [comment]
Last one added at PR is also related with filed issues.
Seems than now is implemented an AJAX query when we call by "Edition raw" button and the call back were sush as we have not and text area there.
I have applied a  `$(document).ready(function()` wrapping the same code  we use before as change
Also noticed a double dot at this line
		`HTMLHelper::_('script', $basePath . 'lib/codemirror-ce.min.js', array('version' => 'auto'));
And i have correct it.
Now codemirrow in raw edition is back
codemirror_now

As before, not sure if it is the best way, now is working
`

**Comment by infograf768** [comment]
@Valc 
Problem here with the codemirror part. You indeed found out where the issue was but it does not work as is

Screen Shot 2021-08-23 at 11 18 41

I corrected it by using this code instead (here is the diff):
```
diff --git a/administrator/components/com_localise/Field/IniField.php b/administrator/components/com_localise/Field/IniField.php
index b52e65a..f9b50f3 100644
--- a/administrator/components/com_localise/Field/IniField.php
+++ b/administrator/components/com_localise/Field/IniField.php
@@ -45,8 +45,9 @@
 	{
 		HTMLHelper::_('behavior.core');
+		HTMLHelper::_('jquery.framework');
 		$basePath = 'media/vendor/codemirror/';
 		// Load Codemirror
 		HTMLHelper::_('script', $basePath . 'lib/codemirror.min.js', array('version' => 'auto'));
-		HTMLHelper::_('script', $basePath . 'lib/codemirror-ce.min..js', array('version' => 'auto'));
+		HTMLHelper::_('script', $basePath . 'lib/codemirror-ce.min.js', array('version' => 'auto'));
 		HTMLHelper::_('script', $basePath . 'lib/addons.min.js', array('version' => 'auto'));
 		HTMLHelper::_('stylesheet', $basePath . 'lib/codemirror.css', array('version' => 'auto'));
@@ -79,24 +80,28 @@
 
 		Factory::getDocument()->addScriptDeclaration("
-			var editor = CodeMirror.fromTextArea(document.getElementById('" . $this->id . "'), " . json_encode($options) . ");
-			editor.setOption('extraKeys', {
-				'Ctrl-Q': function(cm) {
-					cm.setOption('fullScreen', !cm.getOption('fullScreen'));
-				},
-				'Esc': function(cm) {
-					if (cm.getOption('fullScreen')) cm.setOption('fullScreen', false);
-				}
-			});
-			editor.on('gutterClick', function(cm, n) {
-				var info = cm.lineInfo(n)
-				cm.setGutterMarker(n, 'breakpoints', info.gutterMarkers ? null : makeMarker())
-			})
-			function makeMarker() {
-				var marker = document.createElement('div')
-				marker.style.color = '#822';
-				marker.innerHTML = '●'
-				return marker
-			}
-			Joomla.editors.instances['" . $this->id . "'] = editor;
+			(function($){
+				$(document).ready(function() {
+					var editor = CodeMirror.fromTextArea(document.getElementById('" . $this->id . "'), " . json_encode($options) . ");
+					editor.setOption('extraKeys', {
+						'Ctrl-Q': function(cm) {
+							cm.setOption('fullScreen', !cm.getOption('fullScreen'));
+						},
+						'Esc': function(cm) {
+							if (cm.getOption('fullScreen')) cm.setOption('fullScreen', false);
+						}
+					});
+					editor.on('gutterClick', function(cm, n) {
+						var info = cm.lineInfo(n)
+						cm.setGutterMarker(n, 'breakpoints', info.gutterMarkers ? null : makeMarker())
+					})
+					function makeMarker() {
+						var marker = document.createElement('div')
+						marker.style.color = '#822';
+						marker.innerHTML = '●'
+						return marker
+					}
+					Joomla.editors.instances['" . $this->id . "'] = editor;
+				});
+			})(jQuery);
 		");
 
```
Please test that code.

NOTE:
Modified here your patch to test by taking off the type changes in the xml as these are always lowercase
example
```
- type="translationsclient" OK
+ type="Translationsclient" Wrong
```

Php type fields indeed want an uppercase as first letter in their name.

As soon as I have merged my changes

**Comment by Valc** [comment]
@infograf768

After apply your patch i come back to my initial console error message, that does not macth with your actual console error message

after_jm_patch

I will attach also the pacake i use with all my mods added, maybe i am forgueting some stuff to send at the PRs branches.

[com_localise-5.0.0-beta2.zip](https://github.com/infograf768/j4localise/files/7031897/com_localise-5.0.0-beta2.zip)

Using Meld or similar diff tool maybe you can to see faster the diff we have not aplied.

I think is issued due AJAX call back, maybe i am wrong.

Regards.

**Comment by Valc** [comment]
@infograf768
I had not correctly applied your patch. Now is working as fine with your patch. Here same than before with your patch:
[com_localise-5.0.0-beta2_with_codemirror_JM_patch_also_working.zip](https://github.com/infograf768/j4localise/files/7032751/com_localise-5.0.0-beta2_with_codemirror_JM_patch_also_working.zip)

**Comment by infograf768** [comment]
OK. I merge my changes including yours for the Uppercase fields type name.
Thanks.

You now have to pick up the master branch and update your test branch.
Closing this.

Next issue if you have time:
The files included in a package are no more hightlighted in the right column.

**Pull request closed without merging**
