### PR TITLE
[Draft] Delete extrainref [Basic mode] ampliable to advanced mode.

### PR DESCRIPTION
**Pull request by Valc**
@infograf768

Here is the PR about "Delete the extra keys" of the translation that you commented from here:

https://github.com/infograf768/j4localise/issues/30

What I am sending you now is just a draft, tested, of course, with the "J3" it-IT package.

notinref1

notinref2

`Care due now is deleting ALL not in reference.`

As I told you in the other thread, we should handle the issue of plurals, which in the end are still keys that do not exist in the reference.

In my head I already have it working.

Basically, we have to separate the plurals of that "not in reference" section and create a unique one for the plurals.

This is not complicated, the structure of the current code follows a pattern that makes it easy to include it.

I just need to complete some arrays correctly.

You have already given me that information in the other thread.

The advantage of arrays is that elements can be added and removed easily, and it is enough to compare each "notinref" key against each array to determine if is a required extra in translation, a plural case or a real key not in reference en-GB

```
$plural_cases = array(
                                    '_ZERO',
                                    '_ONE',
                                    '_TWO',
                                    '_FEW',
                                    '_MANY',
                                    '_OTHER'
);

$plural_equivalent_cases = array(
                                    '_ONE'  =>  '_1',
                                    '_OTHER'  =>  '_MORE'
);
```

Add "_MANY"  at the end of the key  is also equivalent to add "_6"? Joomla API resolve both cases?

Ready to go to the advanced mode after solve issues of this PR and suggestions? :D

### CODE REVIEW

**Comment by infograf768** [comment]
Hmm.
Deleting globally what is Not in reference is a problem with plurals. It can't be done.

 Look what we have for Russian (you saw what it was for Welsh in https://github.com/infograf768/j4localise/issues/30 )
```
	public static function getPluralSuffixes($count)
	{
		if ($count == 0)
		{
			$return = array('0');

		} else {
			$return = array(($count%10==1 && $count%100!=11 ? '1' : ($count%10>=2 && $count%10<=4 && ($count%100<10 || $count%100>=20)? '2' : 'MORE')));

		}

		return $return;
	}
```
gives
COM_CONTENT_N_ITEMS_PUBLISHED_1="%d материал успешно опубликован."
COM_CONTENT_N_ITEMS_PUBLISHED_2="%d материала успешно опубликовано."
COM_CONTENT_N_ITEMS_PUBLISHED="%d материалов успешно опубликовано."

in en-GB we have
COM_CONTENT_N_ITEMS_PUBLISHED="%d articles published."
COM_CONTENT_N_ITEMS_PUBLISHED_1="Article published."

Remark that _1 is very different in Russian and English
Remark that _MORE is not used.

in fr-FR, we have
COM_CONTENT_N_ITEMS_PUBLISHED_ONE="Article publié."
COM_CONTENT_N_ITEMS_PUBLISHED_OTHER="%d articles publiés."

where in fact _OTHER is unnecessary as we could have for the plural
COM_CONTENT_N_ITEMS_PUBLISHED="%d articles publiés."

Much too complex to handle imho.

**Comment by Valc** [comment]
> gives
In this case is the only important is what "gives" Joomla API to use as  plural and not from what language is used or not, or the sense about why that language  is using that plural or not.

The list for plural cases than Joomla API can handle is a limited amount of cases and we are handling only the already present within a particular language file (we are not creating new plural cases in this moment).

`Remark that _MORE is not used.`

If not used but is allowed use it, needs to be revised as "$plural_cases"

`Deleting globally what is Not in reference is a problem with plurals. It can't be done.`

I think so.

Let me try my idea and revise it at the next PR, please.

We also can ask at our forum about what plural cases have they applied on each language than use it. Not the sense of use it, only what they add as plural at the end of a key.

**Comment by infograf768** [comment]
Joomla API  has absolutely no limitation on the use of plural suffixes.
All depend on the localise.php `getPluralSuffixes($count)` function for each language and the resulting `$count` of items concerned.

Crowdin forces some suffixes per language (not sure they can be modified by whoyouknow). Or when a TT does not use crowdin (Russian) they can be whatever they like.

----------------
> Remark that _MORE is not used.
> If not used but is allowed use it, needs to be revised as "$plural_cases"

No way to know if it is a plural or not. Sometimes the key does not include `N_ITEMS` as I was systematically coding in the past.

**Comment by Valc** [comment]
@infograf768
If it is as you say, this PR can be an example in case it can be adapted for something less conflictive and start another more manageable. So, you can close it.

In the other thread you were commenting "add checkboxes" as for "text changes".

In this case, no new button is required.

The user can enter the "not in reference" section and select which keys he wants to delete from the list of extras or which keys not:solve all cases.

Then "Save" or "Apply"

We continue with this alternative?

**Comment by infograf768** [comment]
> The user can enter the "not in reference" section and select which keys he wants to delete from the list of extras or which keys not: and solve all cases from edit view.

> Then "Save" or "Apply" (or by Ajax call do it at the moment "one by one")

> We continue with this alternative?

Looks like this would be the best solution. Ajax would be great. If possible taking into account multiple files.
(The model has been updated by https://github.com/infograf768/j4localise/pull/33)

**Comment by Valc** [comment]
@infograf768

At the same time that I was creating the other PR to handle this matter in a simpler way, I have been making some progress on this one.

I have managed to load the plural "validator" by loading getPluralSuffixes ($ count) of each language in our code.

This alone would lead to nothing.

In the "package" view, two new blank fields would have to be added.

1. "Plurals"
2. "keys to keep"

- If the user does not have extra plurals or cases to keep, he should fill those fields with "null"
- If the user does not fill them in properly for the language he wants to translate, the deletion will be aborted.
- Only if the user has filled in with "null" or with a list of valid plural endings, for that language the deletion would be executed, creating the "plural" and "keep as extra" sections if present.

I am not going to continue adding lines of code for now, I write it down as a possible way out.

The simple way seems is winning at the moment

**Pull request closed without merging**
