### PR TITLE
Packagefile revision2 (Revision 1 was mixing different PRs content)

### PR DESCRIPTION
**Pull request by Valc**
Similar to the TranslationsField revision case:

**Before:**

1. It was getting options from all the tags when it only needs the refrence and the target language tag to help on each translation language task.
2. No reference language tag, target language tag, o mandatory files set was used there.
3. "scan" is very helpful at non core extensions, but was adding duplicated options if not "protection against duplicated" from a previous PR that was helping a bit there. 

**Now**

1. The reference and target tags and mandatory files are there making the task
2. No more duplicated cases comming from other languages
3. No more than the reference and the target language files sets.
4. Added a new field to get the extension name and be able to work togueter with the translations list, to show only the list of files than matches an extension name, by language selected. At core packs this field have not many sense, but at non core seems very useful.
5. Be able to create "maserfile_Extensionname" xml with the selected set of files to be used as "highlighted" reference for each language selected.

**Also:**

- Update the "edit packagefile" view to get same html output than with "package edit" view
- The non core packages, when "download", was still using the prefix "xx-XX" at xml: now is solved.
- And other litle issues that i found but i does not remember now :D

The code structure to handle ajax querys has been almost all reused to apply this PR
The main diff is than now is handling 2 html outputs at time, using an object at model function to reply.

Here some outputs:

new1

Now i know!! it-IT have not a com_localise translation ready!! grrrrr (but their J3 core pack has been wonderfull to test extension names).

It can to be improved, but at the moment will match almost all standar format cases. Odd formats needs one field more (such as with odd sufixes cases, but adjusted to extensions names)

now2

You and me have a com_localise translation started:

now3

No extension name selected when Spanish is selected.

now4

Again no extension name selected but this time with it-IT  selected and him J3 core pack installed.

And now imagine than that list are really non core files to show and handle as separate packages, and not a trick or test case to explain the feature.

now6

Getting the master package to download:

now5

Utch!

### CODE REVIEW

**Comment by infograf768** [comment]
Please adapt to https://github.com/infograf768/j4localise/pull/28 merged

**Comment by infograf768** [comment]
Note:
we should change packversion to not be required for packagefile.xml, and therefore check if empty and change
`$text .= "\t" . '<version>' . $data['version'] . '.' . $data['packversion'] . '</version>' . "\n";`

to take off the period if `$data['packversion']` is empty.

**Comment by Valc** [comment]
> Note:
> we should change packversion to not be required for packagefile.xml, and therefore check if empty and change
> `$text .= "\t" . '<version>' . $data['version'] . '.' . $data['packversion'] . '</version>' . "\n";`
> 
> to take off the period if `$data['packversion']` is empty.

Now i think you have access to my clone. Feel you free to colaborate from the PRs i send.
In this case i think you have more clear than me what changes are required to apply with only one attempt :)

**Comment by infograf768** [comment]
hmm. Not sure about this PR.
A 3rd party extension pack may contain files for various extensions part of the same package, i.e. a plugin, a module, a component, a library, this in site or admin folders. They may not have the same basic name.

With this patch, and if we choose an extension name in the new field, we lose that ability. For example if we had `com_localise` and `plg_system_localisation`, we can't add this last one if filtered.

On the opposite, if another 3pd creates an extension called `mod_localise, it would be displayed in the list.

Also, if we have multiple plugins which name is the same, but folder is different, we may have some confusion.
`plg_sampledata_testing` and `plg_system_testing`

If we do not select an extension name, then the install pack will have no extension name in its manifest.

My suggestion is to take off completely this new feature.

Also, please correct the constants in the xml from
```
label="COM_LOCALISE_LABEL_PACKAGEFILE_EXTENSION_VERSION"
description="COM_LOCALISE_LABEL_PACKAGEFILE_EXTENSION_VERSION_DESC" />
```

to
```
<field
			id="version"
			name="version"
			type="text"
			required="true"
			label="COM_LOCALISE_LABEL_PACKAGEFILE_VERSION"
			description="COM_LOCALISE_LABEL_PACKAGEFILE_VERSION_DESC" />
```

**Comment by Valc** [comment]
@infograf768

Almost all problems that you have mentioned about the "extensionname" field could be handled.

The only thing that it couldn't do much against is out of the box, like using different extension names for the same extension.

The logical thing would be that in those cases outside the standard one does not try to use that field.

However, I am also into the idea of keeping it simple. Now we can create "master packages" by selecting which files to use and the other languages can duplicate that master and fixed for all cases.

Now it is removed.

**Comment by Valc** [comment]
Founded a bug when `ArrayHelper::sortObjects($groups[$client], 'text');` is called;

Issued code at `ExtensiontranslationsField.php` file:

```
		foreach ($groups as $client => $extensions)
		{
			if (count($groups[$client]) == 0)
			{
				// Odd case when value is '' due when "render" seems than it make the option as selected="selected" and it crash the validation after ajax call.
				// due is invalid set an option as diabled and selected at same time. Previous line:
				//$groups[$client][] = HTMLHelper::_('select.option', '',  Text::_('COM_LOCALISE_NOTRANSLATION'), 'value', 'text', true);
				// To solve, next line:
				$groups[$client][] = HTMLHelper::_('select.option', 'empty_' . $client,  Text::_('COM_LOCALISE_NOTRANSLATION'), 'value', 'text', true);
			}
			else
			{
				ArrayHelper::sortObjects($groups[$client], 'text');
			}
		}
```



```
		foreach ($groups as $client => &$extensions)
		{
			if (count($groups[$client]) == 0)
			{
				// Odd case when value is '' due when "render" seems than it make the option as selected="selected" and it crash the validation after ajax call.
				// due is invalid set an option as diabled and selected at same time. Previous line:
				//$groups[$client][] = HTMLHelper::_('select.option', '',  Text::_('COM_LOCALISE_NOTRANSLATION'), 'value', 'text', true);
				// To solve, next line:
				$groups[$client][] = HTMLHelper::_('select.option', 'empty_' . $client,  Text::_('COM_LOCALISE_NOTRANSLATION'), 'value', 'text', true);
			}
			else
			{
				sort($extensions);
			}
		}
```

**Comment by infograf768** [comment]
Ref: sorting.

Looks like the `$extensions` array is not alpha ordered, therefore `usort` does not work.
Let's merge this and look at other issues.

Thanks!

**Pull request merged**
