### PR TITLE
Core at non core

### PR DESCRIPTION
**Pull request by Valc**
@infograf768 
This one will solve the issue at packagefile view, that actually is showing core files to select. After PR:
core-at-non-core-now

### CODE REVIEW

**Comment by Valc** [comment]
No idea about how i have mixed the prs but to solve only this file needs changes at this PR
administrator/components/com_localise/Field/ExtensiontranslationsField.php

**Comment by infograf768** [comment]
@Valc

 the issue came from the wrong order in media core.xml: administrator should have come before site files.
 I also corrected a missing core file.
 Correction here:
 https://github.com/infograf768/j4localise/commit/164941a6d54bd6743777588fe8d6341123aa608c
 
 Please test again last master with the correction.

**Comment by Valc** [comment]
@infograf768 
> the issue came from the wrong order in media core.xml: administrator should have come before site files.
> I also corrected a missing core file.
> Correction here:
> [164941a](https://github.com/infograf768/j4localise/commit/164941a6d54bd6743777588fe8d6341123aa608c)
> 
> Please test again last master with the correction.

After apply that patch have you tested if at core packae view all is running ok?

Because for me that the only place where the file names should really contain the ".ini" is in the manifest XML, and with your modification they no longer include it.

**Comment by infograf768** [comment]
@valc
In 3.x we listed the ini files in the install.xml
This is no more the case in the packs made with com_localise 5 as we now follow @bakual new installation code (also used on crowdin)
Example:
```
<?xml version="1.0" encoding="UTF-8"?>
<extension client="site" type="language" method="upgrade">
	<name>French (fr-FR)</name>
	<tag>fr-FR</tag>
	<version>4.0.2.1</version>
	<creationDate>2021-09-05</creationDate>
	<author>French translation team : joomla.fr</author>
	<authorEmail>traduction@joomla.fr</authorEmail>
	<authorUrl>http://joomla.fr</authorUrl>
	<copyright>Copyright (C) 2005 - 2021 Joomla.fr and Open Source Matters, Inc. All rights reserved.</copyright>
	<license>http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL</license>
	<description>fr-FR - Site language</description>
	<files>
		<folder>/</folder>
		<filename file="meta">install.xml</filename>
	</files>
	<params />
</extension>
```

**Comment by Valc** [comment]
@infograf768 
> This is no more the case in the packs

Yes, that one is right and we need take in care it when a package is created to download it or when a package xml file is exported or imported.

I means than each package we have created have a realated xml file at folder com_localise/packages
for example, you always keeps updated the "master_core.xml" with last set of core files to include.
And the mine, for example, called "Spanish (es-ES) Language Pack.xml

That one is called when we access from pakages view to package or packagefile views

It is used to fullfill the list of files to include in each case, and that xml should keep the language file names with the ".ini" includes shuch as always or we will begin again to not be able to highlight the files to include at save.

So, i think the new format only needs to be handled from "Download" function os "import" or "export" xml package files (that last 2 i have not revised, i supposed).

Other option is get the mandatory core files from Github, but i think that such as now was working is ok.

**Comment by Valc** [comment]
@infograf768 

After solve an issue with my master branch (seems i push a file to master by mistake) i am able to fetchs again with master at your repo.

After apply your patch that is sorting and keeping out the ".ini" from xml i have not noticed the issue detailed here, and not noticed odd stuff when save or create new packages, so, you can to close the PR due seems solved.

Regards.

**Comment by Valc** [comment]
Oh, wait... now i understand why nothing more is crashed: it is due the xml we call from this custom field used for non core packs is at:

/**media**/com_localise/packages/core.xml

And the other used by "getitem" function that  is used at core packages view  from the TranslationsField is at:

/**administrator**/com_localise/packages/packagename.xml

Simply detailed to remember it, the PR can be closed.

**Pull request closed without merging**
