### PR TITLE
Reformat ini files in extension language folder

### PR DESCRIPTION
**Pull request by infograf768**
AS title says.

Make sure to add a language tag to some com_localise strings (as we took them out 2 days ago), for example:
```
language/fr-FR/fr-FR.com_localise.ini
language/fr-FR/fr-FR.com_localise.sys.ini
```
patch and load 5.0.0-dev 
load com_localise languages manager

Screen Shot 2021-09-07 at 19 38 13

Result
Screen Shot 2021-09-07 at 19 54 53

### CODE REVIEW

**Comment by Valc** [comment]
@infograf768 
Here is working fine.

As extra i also test what happens if i have we both cases at time and is resolved overwitting the "es-ES" over the not "es-ES" without crashes. 

I think this one will happen with the next com_localise release due the update will add the not xx-XX. files where we alrready have the tagged ones.  So, seems that is not problem when happens.

**Comment by infograf768** [comment]
I am a bit lost, sorry.

**Comment by Valc** [comment]
> I am a bit lost, sorry.

Yep... sorry for my poor english

Simply try a fresh beta 4 package installation with this mod:

At com_localise language folder also rename manually  the "en-GB" and "fr-FR"  to use old format file names (the other languages are alrready old formar names), and then install it at your test site.

Then create another pakage with your patch aplied and with all com_localise languages with new format names and update the extension:

Expected result: all our language files will be renamed to normalized format, but the apliead as new translation task will be lost

**Comment by infograf768** [comment]
I do not work anymore on beta4 but on master where all com_localise inis are now in new format.
When we are ready to release a RC, people will have to uninstall first any former com_localise installation.

I just tested by duplicating the ini language files in one of the com_localise folders.
I added the lang tag prefix to both duplicated inis for one language so that we get 4 files, 2 with tag (supposed to be the new ones when extension is updated), 2 without (the older ones already reformatted).

Screen Shot 2021-09-09 at 09 27 13

Then I modified the one with tag by adding a string.

Then I display com_localise languages or translations Managers

Reformattting is done
Screen Shot 2021-09-09 at 09 34 37

Screen Shot 2021-09-09 at 09 45 35

The reformatted files contains the changes (new string) from the file with tag.

Still lost, sorry.

**Comment by Valc** [comment]
@infograf768 
> Then I modified the one with tag by adding a string.

Same test but now add the new text within the not tagged file, save, and then go to display com_localise languages or translations Managers.

Is the new text there overwritted by the prefixed file content?

At the end this one is not a big problem and with time old format will be replaced by new one.

The case such as i say you test now is solved reinstalling the extension and done forever.

And the other, when the case is that the extension is keeping the old format each time is releasing an update, is solved with your code.

**Comment by infograf768** [comment]
> Same test but now add the new text within the not tagged file, save, and then go to display com_localise languages or translations Managers.
> Is the new text there overwritted by the prefixed file content?

I guess not, but to solve this would be extremely complex. Compare all strings in the inis, accept or not the changes, etc.
Merging and thanks for testing.

**Pull request merged**
