### PR TITLE
Update es es

### PR DESCRIPTION
**Pull request by Valc**
@infograf768
Here the update for the translation at  es-ES com_localise language files

Note than we are still using the "es-ES." and seems this one should be replaced by stadarized format

Is the function used to "reformat J3" files skipping them expressly?

### CODE REVIEW

**Comment by infograf768** [comment]
> Is the function used to "reformat J3" files skipping them expressly?

Good question. I did it for core. Did not test anything concerning 3pd.
We could
1. Take off the prefix for com_localise lang strings indeed. New PR necessary. Will do.
2. Implement reformat for extensions containing their language folder. A bit more complex.

In the mean while, please correct the double copyright to joomlacode as it is dead fish and give it to OSM (`<copyright>(C) 2017 - 2021 Open Source Matters. All rights reserved.</copyright>`)and I will merge this PR.

**Comment by Valc** [comment]
> In the mean while, please correct the double copyright to joomlacode as it is dead fish and give it to OSM

Done! :)

**Comment by infograf768** [comment]
tks

**Comment by infograf768** [comment]
com_localise language files prefix reformatted
https://github.com/infograf768/j4localise/commit/42f5dc808a37fcb8a41f36b288290ad99dd4d026

Warning: uninstall master and reinstall or exchange language folder

**Comment by infograf768** [comment]
Remains to do:
`Implement reformat for extensions containing their language folder.`

**Comment by Valc** [comment]
@infograf768 
> com_localise language files prefix reformatted
> [42f5dc8](https://github.com/infograf768/j4localise/commit/42f5dc808a37fcb8a41f36b288290ad99dd4d026)
> 
> Warning: uninstall master and reinstall or exchange language folder

Here is working fine, also without delete the com:localise "language" folder at my test site.

Then deleting the old folder at beta4 package and at my test site and adding the new  at beta4 package, after install it, also working without issues.

**Pull request merged**
