### PR TITLE
Adapting extensiontranslationsfield to ini without tag + display

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/infograf768/j4localise/pull/26#issuecomment-916833359 Thanks Valc.

I also normalised the display.

Screen Shot 2021-09-11 at 09 42 41

### CODE REVIEW

**Comment by Valc** [comment]
@infograf768
Here is working fine

**Comment by Valc** [comment]
@infograf768 

Before you merge you can also test this variant, due the ExtensiontranslationsField is a bit more complex than the core one.
The case is than it get the files with 2 steps: getting from core folders and then getting from scan.

The new code take that one in care and create a new array to store there all option, and at the end, adds a second  class if the case is missed or extra file, at in-core-folder, in-component-folder, etc. So, at the end we can get "in-core-folder extra", "in-component-folder missed", ect
```
<?php
/**
 * @package     Com_Localise
 * @subpackage  models
 *
 * @copyright   Copyright (C) 2005 - 2015 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
namespace Joomla\Component\Localise\Administrator\Field;

defined('_JEXEC') or die;

use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Filesystem\File;
use Joomla\CMS\Filesystem\Folder;
use Joomla\CMS\Form\Field\GroupedlistField;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\Component\Localise\Administrator\Helper\LocaliseHelper;
use Joomla\Utilities\ArrayHelper;

/**
 * Form Field ExtensionTranslations class.
 *
 * @package     Extensions.Components
 * @subpackage  Localise
 *
 * @since       1.0
 */
class ExtensiontranslationsField extends GroupedlistField
{
	/**
	 * The field type.
	 *
	 * @var    string
	 */
	protected $type = 'Extensiontranslations';

	/**
	 * Method to get a list of options for a list input.
	 *
	 * @return  array    An array of JHtml options.
	 */
	protected function getGroups()
	{
		$params         = ComponentHelper::getParams('com_localise');
		$reftag	        = $params->get('reference', '');

		$formdata       = $this->form->getData();
		$langtag        = $formdata["language"];

		$istranslation  = $reftag != $langtag;

		$coreadminfiles = array();
		$coresitefiles  = array();
		$noncorefiles   = array();
		$allfiles       = array();
		$missedfiles    = array();
		$extrafiles     = array();

		$requiredtags   = array($reftag);

		if ($istranslation)
		{
			$requiredtags[] = $langtag;
		}

		$requiredtypes  = array('_thirdparty');

		if (empty($reftag))
		{
			$reftag = 'en-GB';
		}

		// Remove '.ini' from values
		if (is_array($this->value))
		{
			foreach ($this->value as $key => $val)
			{
				$ext = File::getExt($val);

				if ($ext == "ini")
				{
					$this->value[$key] = substr($val, 0, -4);
				}
			}
		}

		$xml            = simplexml_load_file(JPATH_ROOT . '/media/com_localise/packages/core.xml');
		$coreadminfiles = (array) $xml->administrator->children();
		$coresitefiles  = (array) $xml->site->children();

		$coresitefiles  = $coresitefiles['filename'];
		$coreadminfiles = $coreadminfiles['filename'];

		$coreadminfiles = self::suffix_array_values($coreadminfiles, '.ini');
		$coresitefiles  = self::suffix_array_values($coresitefiles, '.ini');

		$package = (string) $this->element['package'];
		$groups  = array('Site' => array(), 'Administrator' => array());

		foreach (array('Site', 'Administrator') as $client)
		{
			$allfiles[$client]     = array();
			$noncorefiles[$client] = array();
			$extrafiles[$client]   = array();

			$path                  = constant('LOCALISEPATH_' . strtoupper($client)) . '/language';

			if (Folder::exists($path))
			{
				$tags = Folder::folders($path, '.', false, false, array('overrides', '.svn', 'CVS', '.DS_Store', '__MACOSX'));

				if ($tags)
				{
					foreach ($tags as $tag)
					{
						if (!in_array($tag, $requiredtags))
						{
							continue;
						}

						$allfiles[$client][$tag] = array();
						$files                   = Folder::files("$path/$tag", ".ini$");

						if ($client == 'Site')
						{
							$noncorefiles[$client] = array_diff($files, $coresitefiles);
						}
						elseif ($client == 'Administrator')
						{
							$noncorefiles[$client] = array_diff($files, $coreadminfiles);
						}

						foreach ($files as $file)
						{

							if (!in_array($file, $noncorefiles[$client]))
							{
								continue;
							}

							if ($file == 'joomla.ini')
							{
								$key      = 'joomla';
								$value    = Text::_('COM_LOCALISE_TEXT_TRANSLATIONS_JOOMLA');
								$origin   = LocaliseHelper::getOrigin('', strtolower($client));
								$disabled = $origin != $package && $origin != '_thirdparty';
							}
							else
							{
								$key      = substr($file, 0, strlen($file) - 4);
								$value    = $key;
								$origin   = LocaliseHelper::getOrigin($key, strtolower($client));
								$disabled = $origin != $package && $origin != '_thirdparty';
							}

							if (!array_key_exists($key, $groups[$client]))
							{
								$allfiles[$client][$tag][] = $key;
								$groups[$client][$key] = HTMLHelper::_('select.option', strtolower($client) . '_' . $key, $value, 'value', 'text', false);
								$groups[$client][$key]->class = "in-core-folder";
							}
						}
					}
				}
			}
		}

		$scans = LocaliseHelper::getScans();

		foreach ($scans as $scan)
		{
			$prefix     = $scan['prefix'];
			$suffix     = $scan['suffix'];
			$type       = $scan['type'];
			$client     = ucfirst($scan['client']);
			$path       = $scan['path'];
			$folder     = $scan['folder'];
			$extensions = Folder::folders($path);

			foreach ($extensions as $extension)
			{
				// Take off core extensions
				$file = "$prefix$extension$suffix.ini";

				if (($client == 'Site' && !in_array($file, $coresitefiles)) || ($client == 'Administrator' && !in_array($file, $coreadminfiles)))
				{
					if (Folder::exists("$path$extension/language"))
					{
						// Scan extensions folder
						$tags = Folder::folders("$path$extension/language");

						foreach ($tags as $tag)
						{
							if (!in_array($tag, $requiredtags))
							{
								continue;
							}

							$file   = "$path$extension/language/$tag/$prefix$extension$suffix.ini";

							//Getting the $origin to avoid add, for example, overrides
							$origin = LocaliseHelper::getOrigin("$prefix$extension$suffix", strtolower($client));

							if (File::exists($file) && in_array($origin, $requiredtypes))
							{
								if (!array_key_exists("$prefix$extension$suffix", $groups[$client]))
								{
									$groups[$client]["$prefix$extension$suffix"] = HTMLHelper::_(
											'select.option', strtolower($client) . '_' . "$prefix$extension$suffix", "$prefix$extension$suffix", 'value', 'text', false
									);

									$allfiles[$client][$tag][] = "$prefix$extension$suffix";
									$groups[$client]["$prefix$extension$suffix"]->class = "in-$type-folder";
								}
							}
						}
					}
				}
			}
		}

		foreach (array('Site', 'Administrator') as $client)
		{
			$missedfiles[$client] = array();
			$extrafiles[$client]  = array();

			if (!empty($allfiles[$client][$reftag]) && !empty($allfiles[$client][$langtag]))
			{
				$missedfiles[$client] = array_diff($allfiles[$client][$reftag], $allfiles[$client][$langtag]);
				$extrafiles[$client]  = array_diff($allfiles[$client][$langtag], $allfiles[$client][$reftag]);

				if (!empty($missedfiles[$client]))
				{
					foreach ($missedfiles[$client] as $id => $file)
					{
						$prevclass = $groups[$client][$file]->class;
						$groups[$client][$file]->class = $prevclass . " missed";
					}
				}

				if (!empty($extrafiles[$client]))
				{
					foreach ($extrafiles[$client] as $id => $file)
					{
						$prevclass = $groups[$client][$file]->class;
						$groups[$client][$file]->class = $prevclass . " extra";
					}
				}
			}
		}

		foreach ($groups as $client => $extensions)
		{
			if (count($groups[$client]) == 0)
			{
				$groups[$client][] = HTMLHelper::_('select.option', '',  Text::_('COM_LOCALISE_NOTRANSLATION'), 'value', 'text', true);
			}
			else
			{
				ArrayHelper::sortObjects($groups[$client], 'text');
			}
		}

		// Merge any additional options in the XML definition.
		$groups = array_merge(parent::getGroups(), $groups);

		return $groups;
	}

	/**
	 * Method to add a suffix to an array.
	 *
	 * @param   array   $array   An array of core files.
	 * @param   string  $suffix  The suffix to add to each file.
	 *
	 * @return  array   The modified array
	 */
	public static function suffix_array_values($array, $suffix = '')
	{
		if (!is_array($array))
		{
			return false;
		}

		// Suffix the values and respect the keys
		foreach ($array as $key => $value)
		{
			if (!is_string($value))
			{
				continue;
			}

			$array[$key] = $value . $suffix;
		}

		return $array;
	}
}
```

**Comment by infograf768** [comment]
In fact, I fail to understand the reason behind adding a class. It looks overdoing for me.

**Comment by Valc** [comment]
Because adding the class could help visually to understand why a package will not be able to be downloaded.

For example, if "missed" files are highlighted with a red dot to the left of the file name, the user will be able to understand that they must first "start" that file from "translations"

An orange dot next to the extras may indicate that either there are too many files in the package or that the extra file is actually going to be included in the package if you select it.

Esa es la idea :D

**Comment by infograf768** [comment]
I would appreciate display examples of these cases please. Extensions to install and views: css don't need to be perfect.

**Comment by Valc** [comment]
@infograf768

Ok then, here we are:

unchecked
when-checked

The PHP code is updated at the top of the page.
I also have added the css file at oue **/media/com_localise/css/packagefile.css** with this content due seems toomuch get again the full localise.css to add only that low amount of lines:

```
option.missed::before {
  content: "● ";
  color: red;
}
option.extra::before {
  content: "● ";
  color: darkorange;
}
option.missed {
  color: red;
}
option.extra {
  color: darkorange;
}
```

As first real sample, my mod called "mod_core_translations_assistant" that only have the en-GB language and i really have not started the "es-ES" translation.

We are at J4 and me does not know what translated extensions from the em-GB can keep old files there.

I know than for core pack, usually the en-GB is adding or deleting language files from the language packs. This one also can happen with non-core extensions with more than one language file to handle.

Case they add, we need start the translation from the "translations" view and case they delete, we need uncheck that file from our translation.. or not

Dye other case with core packs than happened some years ago was than we was keeping as extra some files (com_weblinks?) due that component was not included yet as core extension. And we was continuing including that files in translations due posible user migrations issues (if i remember wrong, sure you remember it).

So, the cases can happen and this can help visually to take.

**Comment by Valc** [comment]
If also id changed the packagefile.xml to add a desc to translations fieldset and is added the new at com_localise language file we can get this:
with-desc

Code and CSS not updated here.. i need siesta

**Comment by infograf768** [comment]
I am a bit lost in translation here ;)
What do you exactly mean by `missed`. I guess it rather should be in English `missing` but what is exactly a `missing file` or is it `missing translation` for the language selected?

**Comment by Valc** [comment]
@infograf768 
For sure you are lost in translation due my poor english!!! XD
With "missed" i meant to say "is it missing translation for the language selected", or "File without translation for the selected language"

**Comment by Valc** [comment]
@infograf768

All the changes now are applied at the top of the page.

I also have replaced all matches of "missed" to "missing" within de code

**Comment by infograf768** [comment]
Closing as @valc is proposing a more extensive change.

**Pull request closed without merging**
