### PR TITLE
Add api folder

### PR DESCRIPTION
**Pull request by DenysNosov**
Fix error:

`Notice: Undefined index: api in /run/media/den/server/http/public_html/lang.j/public_html/uk-UA_4.x/administrator/components/com_localise/Helper/LocaliseHelper.php on line 772`

### CODE REVIEW

**Comment by infograf768** [comment]
I do not have this issue here. How do you get it? 
We don't need the api reference language as it is a copy of the admin joomla.ini + install.xml and metadata.xml
Once the langmetadata.xml is created for `api` the package is made by copying the admin joomla.ini.
See PackageModel.

Screen Shot 2021-09-03 at 08 01 39

**Comment by infograf768** [comment]
hmm, I got an issue now but different than yours.
```
Warning: file_get_contents(/Applications/MAMP/htdocs/sample/joomla40/administrator/components/com_localise/customisedref/stable_joomla_releases.txt): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/sample/joomla40/administrator/components/com_localise/Helper/LocaliseHelper.php on line 777
```

**Comment by infograf768** [comment]
I think I found it: one has to save the options a first time before displaying the translations page.

**Comment by DenysNosov** [comment]
Okay👍 Thanks you!

**Comment by infograf768** [comment]
To test, while in Languages page, purge com_localise. 
Then uninstall com_localise. 
Install beta4 (https://github.com/infograf768/j4localise/releases/tag/5.0.0-beta4) and when you get again in languages page click on Options.

Can you close it if you do not have the error again.

**Pull request closed without merging**
